"""Authentic Indian Craft Fixtures & Fallback Data for ShilpSetu AI
MoSJE - Department of Social Justice and Empowerment
Target Beneficiary Corporates: NBCFDC & NSFDC
"""

CRAFT_FIXTURES = {
    "chanderi_saree": {
        "id": "CRAFT-NSFDC-001",
        "craft_category": "Handloom Textiles",
        "title_en": "Handwoven Pure Chanderi Silk Zari Border Saree",
        "title_hi": "पारंपरिक हाथ से बुनी चंदेरी सिल्क ज़री बॉर्डर साड़ी",
        "description_en": "Exquisite handwoven Chanderi silk saree crafted on traditional pit looms with gossamer-light texture, adorned with intricate gold zari booti motifs and a contrast border.",
        "description_hi": "मध्य प्रदेश के पारंपरिक बुनकरों द्वारा हथकरघे पर तैयार की गई हल्की और भव्य चंदेरी सिल्क साड़ी, जिसमें बारीक ज़री का काम और पारंपरिक बूटी डिज़ाइन है।",
        "materials_used": ["Mulberry Silk Warp", "Fine Cotton Weft", "Pure Zari Metallic Thread"],
        "technique": "Interlocking Weft Pit-Loom Weaving (Eknaliya)",
        "estimated_hours": 18,
        "raw_material_cost_estimate_inr": 1400.0,
        "seo_keywords": ["chanderi silk", "handloom saree", "zari border", "indian handloom", "wedding ethnic wear", "traditional drape"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Chanderi Fabric (GI Tag #7)",
        "beneficiary_id": "NSFDC-MP-77291",
        "cluster_pin": "473446",
        "gi_tag_serial": "GI-0007-0042",
        "sample_image_url": "/static/samples/chanderi_saree.jpg",
        "artisan_name": "Ramesh Chandra Koli",
        "artisan_community": "Scheduled Caste Weaver Collective",
        "sample_transcript_hi": "यह शुद्ध चंदेरी सिल्क की साड़ी है। इसे बनाने में मुझे और मेरे परिवार को करीब अठारह घंटे लगे हैं। इसमें जरी का पल्लू और बारीक बूटी का काम है। कच्चा माल धागा और जरी लगभग चौदह सौ रुपये का लगा है।",
        "sample_transcript_en": "This is a pure Chanderi silk saree. It took me and my family about eighteen hours on the handloom. It features zari pallu and delicate booti work. Raw silk yarn and zari cost around fourteen hundred rupees."
    },
    "gorakhpur_terracotta": {
        "id": "CRAFT-NBCFDC-002",
        "craft_category": "Terracotta & Pottery",
        "title_en": "Handcrafted Indian Terracotta Cooking Handi Pot",
        "title_hi": "हस्तनिर्मित भारतीय टेराकोटा हांडी / कलश",
        "description_en": "Natural red clay cooking handi pot shaped with traditional wheel-throwing and hand-burnished finish, fired in indigenous low-smoke kilns for healthy, alkaline culinary cooking.",
        "description_hi": "प्राकृतिक शुद्ध लाल मिट्टी से चाक पर गढ़ी गई पारंपरिक टेराकोटा हांडी, जो धीमी आंच पर स्वास्थ्यवर्धक भोजन पकाने के लिए आदर्श है।",
        "materials_used": ["Gorakhpur Silt Riverbed Clay", "Natural Wood Ash", "Organic Gum Binder"],
        "technique": "Wheel Throwing & Clay Appliqué Hand Carving",
        "estimated_hours": 6,
        "raw_material_cost_estimate_inr": 180.0,
        "seo_keywords": ["terracotta handi", "gorakhpur terracotta", "clay cooking pot", "eco friendly home decor", "handmade pottery", "indian terracotta urn"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Gorakhpur Terracotta (GI Tag #687)",
        "beneficiary_id": "NBCFDC-UP-18492",
        "cluster_pin": "273001",
        "gi_tag_serial": "GI-0687-0105",
        "sample_image_url": "/terracotta_pot_raw.png",
        "raw_image_url": "/terracotta_pot_raw.png",
        "clean_image_url": "/terracotta_pot_clean.png",
        "artisan_name": "Sunil Kumar Prajapati",
        "artisan_community": "Backward Classes Potter Community",
        "sample_transcript_hi": "यह गोरखपुर का टेराकोटा मिट्टी की पारंपरिक हांडी है। तालाब की शुद्ध मिट्टी से चाक पर बनाया है। नक्काशी करने और भट्टी में पकाने में छह घंटे का समय लगा। मिट्टी और ईंधन का खर्चा करीब एक सौ अस्सी रुपये आया।",
        "sample_transcript_en": "This is a handcrafted Gorakhpur terracotta cooking handi pot. Made on the traditional potter's wheel using pure silt clay. Hand carving and kiln firing took six hours. Clay and husk fuel cost around one hundred eighty rupees."
    },
    "dhokra_brass": {
        "id": "CRAFT-NBCFDC-003",
        "craft_category": "Dhokra & Metalware",
        "title_en": "Bastar Dhokra Lost-Wax Cast Bell Metal Tribal Musician Figurine",
        "title_hi": "बस्तर ढोकरा पारंपरिक लॉस्ट-वैक्स धातु जनजातीय संगीतकार मूर्ति",
        "description_en": "Rare primitive tribal artwork cast using the 4000-year-old cire-perdue (lost wax) process. Every piece is unique as the clay mold must be broken to release the molten brass sculpture.",
        "description_hi": "बस्तर की 4000 वर्ष पुरानी लॉस्ट वैक्स पद्धति से ढली पीतल व कांस्य की जनजातीय संगीतकार प्रतिमा। हर एक शिल्प अद्वितीय और हस्तनिर्मित है।",
        "materials_used": ["Recycled Brass Scraps", "Beeswax Strands", "Riverbed Clay and Cow Dung Core"],
        "technique": "Cire-Perdue (Lost Wax Bell Metal Casting)",
        "estimated_hours": 12,
        "raw_material_cost_estimate_inr": 480.0,
        "seo_keywords": ["dhokra metal craft", "bastar art", "lost wax brass", "tribal figurine", "indian bell metal", "artisan showpiece"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Bastar Dhokra (GI Tag #82)",
        "beneficiary_id": "NBCFDC-CG-90214",
        "cluster_pin": "494001",
        "gi_tag_serial": "GI-0082-0056",
        "sample_image_url": "/static/samples/dhokra_brass.jpg",
        "artisan_name": "Mangal Ram Ghadwa",
        "artisan_community": "Traditional Bell-Metal Artisan Society",
        "sample_transcript_hi": "यह बस्तर का ढोकरा शिल्प है। मोम के धागे बनाकर मिट्टी के सांचे में पीतल ढालकर बनाया है। बारह घंटे की कड़ी मेहनत लगी है। पीतल और मोम का खर्चा लगभग चार सौ अस्सी रुपये है।",
        "sample_transcript_en": "This is Bastar Dhokra craft. Sculpted using wax strings and molten brass poured into clay molds. Took twelve hours of intense labor. Brass scrap and natural wax cost four hundred eighty rupees."
    },
    "madhubani_painting": {
        "id": "CRAFT-NSFDC-004",
        "craft_category": "Folk Painting",
        "title_en": "Authentic Madhubani Handmade Tree of Life Mithila Folk Art",
        "title_hi": "पारंपरिक मधुबनी हाथ से रचित कल्पवृक्ष (ट्री ऑफ लाइफ) लोक चित्रकला",
        "description_en": "Handcrafted on handmade paper using bamboo twigs, nibs, and organic plant pigments. Features the sacred Tree of Life flanked by peacocks, symbolizing cosmic harmony and abundance.",
        "description_hi": "मिथिला की प्राचीन परंपरा में प्राकृतिक वनस्पति रंगों और बांस की तीली से हस्तनिर्मित कागज पर उकेरी गई कल्पवृक्ष एवं मोर की मंगलकारी पेंटिंग।",
        "materials_used": ["Handmade Sun-dried Paper", "Natural Mineral & Plant Pigments", "Bamboo Twig Nib Pens"],
        "technique": "Kachni & Bharni Line Freehand Folk Painting",
        "estimated_hours": 10,
        "raw_material_cost_estimate_inr": 250.0,
        "seo_keywords": ["madhubani painting", "mithila art", "tree of life", "handmade folk art", "bihar painting", "wall art"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Madhubani Paintings (GI Tag #105)",
        "beneficiary_id": "NSFDC-BR-34190",
        "cluster_pin": "847211",
        "gi_tag_serial": "GI-0105-0089",
        "sample_image_url": "/static/samples/madhubani_art.jpg",
        "artisan_name": "Kavita Devi Paswan",
        "artisan_community": "Mithila Women Artisan Empowerment Group",
        "sample_transcript_hi": "यह मधुबनी की कल्पवृक्ष पेंटिंग है। इसे मैंने बांस की तीली और पत्तियों के प्राकृतिक रंगों से हाथ के बने कागज पर बनाया है। दस घंटे लगे हैं। कागज और रंगों का खर्च दो सौ पचास रुपये है।",
        "sample_transcript_en": "This is a Madhubani Tree of Life painting. Hand-drawn using bamboo twigs and botanical pigments on handmade paper. Took ten hours. Handmade paper and organic colors cost two hundred fifty rupees."
    },
    "copper_wellness_bottle": {
        "id": "SAMPLE-COPPER-001",
        "craft_category": "Metalware & Copper Craft",
        "title_en": "Hand-Engraved Pure Copper Ayurvedic Wellness Bottle",
        "title_hi": "ताम्रकार हस्तशिल्प शुद्ध तांबे की नक्काशीदार पानी की बोतल",
        "description_en": "Exquisite hand-engraved pure copper bottle handcrafted by traditional Thathera/Tambat metalsmiths.",
        "description_hi": "पुणे और मुरादाबाद के पारंपरिक ताम्रकारों द्वारा हाथ से गढ़ी गई शुद्ध तांबे की स्वास्थ्यवर्धक पानी की बोतल।",
        "materials_used": ["Pure Copper", "Natural Lac"],
        "technique": "Tambat Hand-Beaten Copper Craft",
        "estimated_hours": 6.5,
        "raw_material_cost_estimate_inr": 420.0,
        "seo_keywords": ["copper bottle", "tambat craft", "ayurvedic wellness", "hand engraved", "copperware"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Tambat Bell Metal Craft",
        "beneficiary_id": "NBCFDC-MH-42911",
        "cluster_pin": "411002",
        "sample_image_url": "/samples/il_510x638-8231639702_5z4l.jpg",
        "artisan_name": "Vinayak Tambat",
        "artisan_community": "Tambat Metal Artisans Collective"
    },
    "kutch_mirror_tote": {
        "id": "SAMPLE-KUTCH-001",
        "craft_category": "Handloom Textiles",
        "title_en": "Kutch Rabari Mirror-Work Embroidered Handcrafted Tote Bag",
        "title_hi": "कच्छ राबारी पारंपरिक आभला (आईना) कशीदाकारी टोट बैग",
        "description_en": "Vibrant hand-stitched tote bag featuring authentic Kutch Rabari tribal chain-stitch embroidery and hand-set shisha mirrors.",
        "description_hi": "कच्छ के देहाती कारीगरों द्वारा सुई-धागे और असली कांच के टुकड़ों (आभला) से हाथ से काढ़ा गया रंग-बिरंगा झोला।",
        "materials_used": ["Handspun Cotton", "Silk Threads", "Shisha Glass Mirrors"],
        "technique": "Kutch Rabari & Ahir Mirror Embroidery",
        "estimated_hours": 8.5,
        "raw_material_cost_estimate_inr": 580.0,
        "seo_keywords": ["kutch embroidery", "mirror work", "rabari art", "gujarat craft", "boho tote bag"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Kutch Embroidery (GI #37)",
        "beneficiary_id": "NSFDC-GJ-55102",
        "cluster_pin": "370001",
        "sample_image_url": "/samples/il_510x638-8236910436_72ob.jpg",
        "artisan_name": "Pabuben Rabari",
        "artisan_community": "Kutch Pastoralist Women Collective"
    },
    "channapatna_dolls": {
        "id": "SAMPLE-CHANN-001",
        "craft_category": "Woodcraft & Carving",
        "title_en": "Channapatna Eco-Lacquered Wooden Classical Dancer Figurines",
        "title_hi": "चन्नापटना लाख-रंजित लकड़ी की पारंपरिक नृत्यांगना गुड़िया",
        "description_en": "Hand-turned on traditional lathes from Ivory Wood (Aale Mara) and polished with non-toxic natural shellac lacquer.",
        "description_hi": "प्राकृतिक वनस्पति रंगों व लाख से लेपित पारंपरिक चन्नापटना लकड़ी की नर्तकी आकृतियां, 100% गैर-विषाक्त।",
        "materials_used": ["Ivory Wood (Aale Mara)", "Natural Shellac Lacquer", "Organic Vegetable Dyes"],
        "technique": "Channapatna Lacquer Toy Craft",
        "estimated_hours": 5.0,
        "raw_material_cost_estimate_inr": 280.0,
        "seo_keywords": ["channapatna toys", "wooden dolls", "eco friendly toys", "karnataka craft"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Channapatna Toys and Dolls (GI #18)",
        "beneficiary_id": "NBCFDC-KA-66291",
        "cluster_pin": "562160",
        "sample_image_url": "/samples/il_510x638-7342609190_tbrp.jpg",
        "artisan_name": "Mutturaj Gowda",
        "artisan_community": "Karnataka Traditional Toymaker Guild"
    },
    "sanganeri_block_tote": {
        "id": "SAMPLE-SANGA-001",
        "craft_category": "Handloom Textiles",
        "title_en": "Sanganeri Hand Block Printed Quilted Pure Cotton Tote Bag",
        "title_hi": "सांगानेरी प्राकृतिक रंग हाथ ठप्पा छपाई रजाईदार सूती थैला (टोट बैग)",
        "description_en": "Reversible quilted cotton tote crafted with hand-carved teak woodblocks and organic natural dyes.",
        "description_hi": "शीशम की लकड़ी के ठप्पों से प्राकृतिक रंगों द्वारा हाथ से मुद्रित और रजाईदार टांकों से सिला जयपुर का खूबसूरत थैला।",
        "materials_used": ["Pure Cotton", "Natural Indigo & Madder Dyes", "Teak Woodblock"],
        "technique": "Sanganeri Hand Block Woodblock Printing",
        "estimated_hours": 4.5,
        "raw_material_cost_estimate_inr": 280.0,
        "seo_keywords": ["sanganeri print", "hand block printing", "jaipur block print", "quilted bag"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Sanganeri Hand Block Print (GI #52)",
        "beneficiary_id": "NBCFDC-RJ-19203",
        "cluster_pin": "302029",
        "sample_image_url": "/samples/il_510x638-7187465738_62g5.jpg",
        "artisan_name": "Ramgopal Chhipa",
        "artisan_community": "Sanganer Chhipa Community"
    },
    "pichwai_kamdhenu": {
        "id": "SAMPLE-PICH-001",
        "craft_category": "Folk Painting",
        "title_en": "Authentic Nathdwara Pichwai Painting - Sacred Kamdhenu under Kadamba",
        "title_hi": "नाथद्वारा पारंपरिक पिछवाई चित्रकला - कदंब और कामधेनु गौ",
        "description_en": "Masterpiece devotional Pichwai hand-painted on starched cotton fabric using stone and plant pigments with gold leaf.",
        "description_hi": "सूती कपड़े पर प्राकृतिक खनिज रंगों और सोने की स्याही से उकेरी गई नाथद्वारा की पवित्र कामधेनु गाय और कदंब वृक्ष पिछवाई।",
        "materials_used": ["Khadi Cotton", "Stone Pigments", "Gold Foil"],
        "technique": "Nathdwara Pichwai Cloth Painting",
        "estimated_hours": 22.0,
        "raw_material_cost_estimate_inr": 1200.0,
        "seo_keywords": ["pichwai painting", "nathdwara", "kamdhenu", "rajasthan devotional art", "gold leaf painting"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Nathdwara Pichhwai Painting (GI #438)",
        "beneficiary_id": "NBCFDC-RJ-11029",
        "cluster_pin": "313301",
        "sample_image_url": "/samples/il_510x638-8059095608_filp.jpg",
        "artisan_name": "Kanhaiyalal Jangid",
        "artisan_community": "Nathdwara Chitaras Guild"
    }
}

DEFAULT_CRAFT_KEY = "gorakhpur_terracotta"
