"""Authentic Indian Craft Fixtures & Fallback Data for ShilpSetu AI
MoSJE - Department of Social Justice and Empowerment
Target Beneficiary Corporates: NBCFDC & NSFDC
"""

CRAFT_FIXTURES = {
    "chanderi_saree": {
        "id": "CRAFT-NSFDC-001",
        "craft_category": "Handloom Textiles",
        "title_en": "Handwoven Pure Chanderi Silk Zari Border Saree",
        "title_hi": "पारंपरिक हाथ से बुनी चंदेरी सिल्क ज़री बॉर्डर साड़ी",
        "description_en": "Exquisite handwoven Chanderi silk saree crafted on traditional pit looms with gossamer-light texture, adorned with intricate gold zari booti motifs and a contrast border.",
        "description_hi": "मध्य प्रदेश के पारंपरिक बुनकरों द्वारा हथकरघे पर तैयार की गई हल्की और भव्य चंदेरी सिल्क साड़ी, जिसमें बारीक ज़री का काम और पारंपरिक बूटी डिज़ाइन है।",
        "materials_used": ["Mulberry Silk Warp", "Fine Cotton Weft", "Pure Zari Metallic Thread"],
        "technique": "Interlocking Weft Pit-Loom Weaving (Eknaliya)",
        "estimated_hours": 18,
        "raw_material_cost_estimate_inr": 1400.0,
        "seo_keywords": ["chanderi silk", "handloom saree", "zari border", "indian handloom", "wedding ethnic wear", "traditional drape"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Chanderi Fabric (GI Tag #7)",
        "beneficiary_id": "NSFDC-MP-77291",
        "cluster_pin": "473446",
        "gi_tag_serial": "GI-0007-0042",
        "sample_image_url": "/static/samples/chanderi_saree.jpg",
        "artisan_name": "Ramesh Chandra Koli",
        "artisan_community": "Scheduled Caste Weaver Collective",
        "sample_transcript_hi": "यह शुद्ध चंदेरी सिल्क की साड़ी है। इसे बनाने में मुझे और मेरे परिवार को करीब अठारह घंटे लगे हैं। इसमें जरी का पल्लू और बारीक बूटी का काम है। कच्चा माल धागा और जरी लगभग चौदह सौ रुपये का लगा है।",
        "sample_transcript_en": "This is a pure Chanderi silk saree. It took me and my family about eighteen hours on the handloom. It features zari pallu and delicate booti work. Raw silk yarn and zari cost around fourteen hundred rupees."
    },
    "gorakhpur_terracotta": {
        "id": "CRAFT-NBCFDC-002",
        "craft_category": "Terracotta & Pottery",
        "title_en": "Handcrafted Indian Terracotta Cooking Handi Pot",
        "title_hi": "हस्तनिर्मित भारतीय टेराकोटा हांडी / कलश",
        "description_en": "Natural red clay cooking handi pot shaped with traditional wheel-throwing and hand-burnished finish, fired in indigenous low-smoke kilns for healthy, alkaline culinary cooking.",
        "description_hi": "प्राकृतिक शुद्ध लाल मिट्टी से चाक पर गढ़ी गई पारंपरिक टेराकोटा हांडी, जो धीमी आंच पर स्वास्थ्यवर्धक भोजन पकाने के लिए आदर्श है।",
        "materials_used": ["Gorakhpur Silt Riverbed Clay", "Natural Wood Ash", "Organic Gum Binder"],
        "technique": "Wheel Throwing & Clay Appliqué Hand Carving",
        "estimated_hours": 6,
        "raw_material_cost_estimate_inr": 180.0,
        "seo_keywords": ["terracotta handi", "gorakhpur terracotta", "clay cooking pot", "eco friendly home decor", "handmade pottery", "indian terracotta urn"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Gorakhpur Terracotta (GI Tag #687)",
        "beneficiary_id": "NBCFDC-UP-18492",
        "cluster_pin": "273001",
        "gi_tag_serial": "GI-0687-0105",
        "sample_image_url": "/terracotta_pot_raw.png",
        "raw_image_url": "/terracotta_pot_raw.png",
        "clean_image_url": "/terracotta_pot_clean.png",
        "artisan_name": "Sunil Kumar Prajapati",
        "artisan_community": "Backward Classes Potter Community",
        "sample_transcript_hi": "यह गोरखपुर का टेराकोटा मिट्टी की पारंपरिक हांडी है। तालाब की शुद्ध मिट्टी से चाक पर बनाया है। नक्काशी करने और भट्टी में पकाने में छह घंटे का समय लगा। मिट्टी और ईंधन का खर्चा करीब एक सौ अस्सी रुपये आया।",
        "sample_transcript_en": "This is a handcrafted Gorakhpur terracotta cooking handi pot. Made on the traditional potter's wheel using pure silt clay. Hand carving and kiln firing took six hours. Clay and husk fuel cost around one hundred eighty rupees."
    },
    "dhokra_brass": {
        "id": "CRAFT-NBCFDC-003",
        "craft_category": "Dhokra & Metalware",
        "title_en": "Bastar Dhokra Lost-Wax Cast Bell Metal Tribal Musician Figurine",
        "title_hi": "बस्तर ढोकरा पारंपरिक लॉस्ट-वैक्स धातु जनजातीय संगीतकार मूर्ति",
        "description_en": "Rare primitive tribal artwork cast using the 4000-year-old cire-perdue (lost wax) process. Every piece is unique as the clay mold must be broken to release the molten brass sculpture.",
        "description_hi": "बस्तर की 4000 वर्ष पुरानी लॉस्ट वैक्स पद्धति से ढली पीतल व कांस्य की जनजातीय संगीतकार प्रतिमा। हर एक शिल्प अद्वितीय और हस्तनिर्मित है।",
        "materials_used": ["Recycled Brass Scraps", "Beeswax Strands", "Riverbed Clay and Cow Dung Core"],
        "technique": "Cire-Perdue (Lost Wax Bell Metal Casting)",
        "estimated_hours": 12,
        "raw_material_cost_estimate_inr": 480.0,
        "seo_keywords": ["dhokra metal craft", "bastar art", "lost wax brass", "tribal figurine", "indian bell metal", "artisan showpiece"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Bastar Dhokra (GI Tag #82)",
        "beneficiary_id": "NBCFDC-CG-90214",
        "cluster_pin": "494001",
        "gi_tag_serial": "GI-0082-0056",
        "sample_image_url": "/static/samples/dhokra_brass.jpg",
        "artisan_name": "Mangal Ram Ghadwa",
        "artisan_community": "Traditional Bell-Metal Artisan Society",
        "sample_transcript_hi": "यह बस्तर का ढोकरा शिल्प है। मोम के धागे बनाकर मिट्टी के सांचे में पीतल ढालकर बनाया है। बारह घंटे की कड़ी मेहनत लगी है। पीतल और मोम का खर्चा लगभग चार सौ अस्सी रुपये है।",
        "sample_transcript_en": "This is Bastar Dhokra craft. Sculpted using wax strings and molten brass poured into clay molds. Took twelve hours of intense labor. Brass scrap and natural wax cost four hundred eighty rupees."
    },
    "madhubani_painting": {
        "id": "CRAFT-NSFDC-004",
        "craft_category": "Folk Painting",
        "title_en": "Authentic Madhubani Handmade Tree of Life Mithila Folk Art",
        "title_hi": "पारंपरिक मधुबनी हाथ से रचित कल्पवृक्ष (ट्री ऑफ लाइफ) लोक चित्रकला",
        "description_en": "Handcrafted on handmade paper using bamboo twigs, nibs, and organic plant pigments. Features the sacred Tree of Life flanked by peacocks, symbolizing cosmic harmony and abundance.",
        "description_hi": "मिथिला की प्राचीन परंपरा में प्राकृतिक वनस्पति रंगों और बांस की तीली से हस्तनिर्मित कागज पर उकेरी गई कल्पवृक्ष एवं मोर की मंगलकारी पेंटिंग।",
        "materials_used": ["Handmade Sun-dried Paper", "Natural Mineral & Plant Pigments", "Bamboo Twig Nib Pens"],
        "technique": "Kachni & Bharni Line Freehand Folk Painting",
        "estimated_hours": 10,
        "raw_material_cost_estimate_inr": 250.0,
        "seo_keywords": ["madhubani painting", "mithila art", "tree of life", "handmade folk art", "bihar painting", "wall art"],
        "gi_tag_eligible": True,
        "gi_tag_name": "Madhubani Paintings (GI Tag #105)",
        "beneficiary_id": "NSFDC-BR-34190",
        "cluster_pin": "847211",
        "gi_tag_serial": "GI-0105-0089",
        "sample_image_url": "/static/samples/madhubani_art.jpg",
        "artisan_name": "Kavita Devi Paswan",
        "artisan_community": "Mithila Women Artisan Empowerment Group",
        "sample_transcript_hi": "यह मधुबनी की कल्पवृक्ष पेंटिंग है। इसे मैंने बांस की तीली और पत्तियों के प्राकृतिक रंगों से हाथ के बने कागज पर बनाया है। दस घंटे लगे हैं। कागज और रंगों का खर्च दो सौ पचास रुपये है।",
        "sample_transcript_en": "This is a Madhubani Tree of Life painting. Hand-drawn using bamboo twigs and botanical pigments on handmade paper. Took ten hours. Handmade paper and organic colors cost two hundred fifty rupees."
    }
}

DEFAULT_CRAFT_KEY = "gorakhpur_terracotta"
